############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "" # don't use a slash for home url
weight = 1
hasChildren = true

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Pages"
url = "#"
weight = 3
hasChildren = true

[[main]]
parent = "Pages"
name = "Tag"
url = "tags/"

[[main]]
parent = "Pages"
name = "Category"
url = "categories/"
